[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=/NODEFAULTLIB:MSVCRT"]
[target.aarch64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[target.loongarch64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,-Bsymbolic",
    "-L", "/usr/lib/loongarch64-linux-gnu",
    "-C", "link-arg=-Wl,--no-as-needed",
    "-C", "link-arg=-lGenericCodeGen",
    "-C", "link-arg=-lMachineIndependent",
    "-C", "link-arg=-lOpenCL",
    "-C", "link-arg=-lSPIRV",
    "-C", "link-arg=-lSPIRV-Tools",
    "-C", "link-arg=-lSPIRV-Tools-opt",
    "-C", "link-arg=-lSvtAv1Enc",
    "-C", "link-arg=-lX11",
    "-C", "link-arg=-laom",
    "-C", "link-arg=-latomic",
    "-C", "link-arg=-lavcodec",
    "-C", "link-arg=-lavformat",
    "-C", "link-arg=-lavutil",
    "-C", "link-arg=-lbluray",
    "-C", "link-arg=-lbz2",
    "-C", "link-arg=-lcairo",
    "-C", "link-arg=-lchromaprint",
    "-C", "link-arg=-lcodec2",
    "-C", "link-arg=-ldav1d",
    "-C", "link-arg=-ldrm",
    "-C", "link-arg=-ldvdnav",
    "-C", "link-arg=-ldvdread",
    "-C", "link-arg=-lgdk_pixbuf-2.0",
    "-C", "link-arg=-lgio-2.0",
    "-C", "link-arg=-lglib-2.0",
    "-C", "link-arg=-lglslang",
    "-C", "link-arg=-lgme",
    "-C", "link-arg=-lgnutls",
    "-C", "link-arg=-lgobject-2.0",
    "-C", "link-arg=-lgsm",
    "-C", "link-arg=-ljxl",
    "-C", "link-arg=-ljxl_threads",
    "-C", "link-arg=-llzma",
    "-C", "link-arg=-lm",
    "-C", "link-arg=-lmp3lame",
    "-C", "link-arg=-logg",
    "-C", "link-arg=-lopenjp2",
    "-C", "link-arg=-lopenmpt",
    "-C", "link-arg=-lopus",
    "-C", "link-arg=-lpng",
    "-C", "link-arg=-lpthread",
    "-C", "link-arg=-lrabbitmq",
    "-C", "link-arg=-lrav1e",
    "-C", "link-arg=-lrist",
    "-C", "link-arg=-lrsvg-2",
    "-C", "link-arg=-lshine",
    "-C", "link-arg=-lsnappy",
    "-C", "link-arg=-lsoxr",
    "-C", "link-arg=-lspeex",
    "-C", "link-arg=-lsrt-gnutls",
    "-C", "link-arg=-lssh",
    "-C", "link-arg=-lstdc++",
    "-C", "link-arg=-lswresample",
    "-C", "link-arg=-lswscale",
    "-C", "link-arg=-ltheoradec",
    "-C", "link-arg=-ltheoraenc",
    "-C", "link-arg=-ltwolame",
    "-C", "link-arg=-lva",
    "-C", "link-arg=-lva-drm",
    "-C", "link-arg=-lva-x11",
    "-C", "link-arg=-lvdpau",
    "-C", "link-arg=-lvorbis",
    "-C", "link-arg=-lvorbisenc",
    "-C", "link-arg=-lvpx",
    "-C", "link-arg=-lwebp",
    "-C", "link-arg=-lwebpmux",
    "-C", "link-arg=-lx264",
    "-C", "link-arg=-lx265",
    "-C", "link-arg=-lxml2",
    "-C", "link-arg=-lxvidcore",
    "-C", "link-arg=-lz",
    "-C", "link-arg=-lzmq",
    "-C", "link-arg=-lzvbi"
]

[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
]
#[target.'cfg(target_os="linux")']
# glibc-static required, this may fix https://github.com/rustdesk/rustdesk/issues/9103, but I do not want this big change
# this is unlikely to help also, because the other so files still use libc dynamically
#rustflags = [
#    "-C", "link-args=-Wl,-Bstatic -lc -Wl,-Bdynamic"
#]
[net]
git-fetch-with-cli = true
